"""The currencies a salary can be in: ISO 4217 codes, with their English names.

Generated from the `currency` and `currency_name` columns of the vendored places data (backend/data/geo/countries.csv,
see the NOTICE there), then corrected by hand where that data is behind or not ISO (see ADJUSTMENTS). It is a list in code,
not a table: nothing is converted or rated, a code is only recorded and shown next to the amount.
"""

DEFAULT_CURRENCY = "USD"

# What the places data says, one entry per distinct code.
_FROM_PLACES_DATA = {
    "AAD": "Antarctican dollar",
    "AED": "United Arab Emirates dirham",
    "AFN": "Afghan afghani",
    "ALL": "Albanian lek",
    "AMD": "Armenian dram",
    "ANG": "Netherlands Antillean guilder",
    "AOA": "Angolan kwanza",
    "ARS": "Argentine peso",
    "AUD": "Australian dollar",
    "AWG": "Aruban florin",
    "AZN": "Azerbaijani manat",
    "BAM": "Bosnia and Herzegovina convertible mark",
    "BBD": "Barbadian dollar",
    "BDT": "Bangladeshi taka",
    "BHD": "Bahraini dinar",
    "BIF": "Burundian franc",
    "BMD": "Bermudian dollar",
    "BND": "Brunei dollar",
    "BOB": "Bolivian boliviano",
    "BRL": "Brazilian real",
    "BSD": "Bahamian dollar",
    "BTN": "Bhutanese ngultrum",
    "BWP": "Botswana pula",
    "BYN": "Belarusian ruble",
    "BZD": "Belize dollar",
    "CAD": "Canadian dollar",
    "CDF": "Congolese Franc",
    "CHF": "Swiss franc",
    "CLP": "Chilean peso",
    "CNY": "Chinese yuan",
    "COP": "Colombian peso",
    "CRC": "Costa Rican colón",
    "CUP": "Cuban peso",
    "CVE": "Cape Verdean escudo",
    "CZK": "Czech koruna",
    "DJF": "Djiboutian franc",
    "DKK": "Danish krone",
    "DOP": "Dominican peso",
    "DZD": "Algerian dinar",
    "EGP": "Egyptian pound",
    "ERN": "Eritrean nakfa",
    "ETB": "Ethiopian birr",
    "EUR": "Euro",
    "FJD": "Fijian dollar",
    "FKP": "Falkland Islands pound",
    "GBP": "British pound",
    "GEL": "Georgian lari",
    "GHS": "Ghanaian cedi",
    "GIP": "Gibraltar pound",
    "GMD": "Gambian dalasi",
    "GNF": "Guinean franc",
    "GTQ": "Guatemalan quetzal",
    "GYD": "Guyanese dollar",
    "HKD": "Hong Kong dollar",
    "HNL": "Honduran lempira",
    "HTG": "Haitian gourde",
    "HUF": "Hungarian forint",
    "IDR": "Indonesian rupiah",
    "ILS": "Israeli new shekel",
    "INR": "Indian rupee",
    "IQD": "Iraqi dinar",
    "IRR": "Iranian rial",
    "ISK": "Icelandic króna",
    "JMD": "Jamaican dollar",
    "JOD": "Jordanian dinar",
    "JPY": "Japanese yen",
    "KES": "Kenyan shilling",
    "KGS": "Kyrgyzstani som",
    "KHR": "Cambodian riel",
    "KMF": "Comorian franc",
    "KPW": "North Korean Won",
    "KRW": "Won",
    "KWD": "Kuwaiti dinar",
    "KYD": "Cayman Islands dollar",
    "KZT": "Kazakhstani tenge",
    "LAK": "Lao kip",
    "LBP": "Lebanese pound",
    "LKR": "Sri Lankan rupee",
    "LRD": "Liberian dollar",
    "LSL": "Lesotho loti",
    "LYD": "Libyan dinar",
    "MAD": "Moroccan dirham",
    "MDL": "Moldovan leu",
    "MGA": "Malagasy ariary",
    "MKD": "Denar",
    "MMK": "Burmese kyat",
    "MNT": "Mongolian tögrög",
    "MOP": "Macanese pataca",
    "MRU": "Mauritanian ouguiya",
    "MUR": "Mauritian rupee",
    "MVR": "Maldivian rufiyaa",
    "MWK": "Malawian kwacha",
    "MXN": "Mexican peso",
    "MYR": "Malaysian ringgit",
    "MZN": "Mozambican metical",
    "NAD": "Namibian dollar",
    "NGN": "Nigerian naira",
    "NIO": "Nicaraguan córdoba",
    "NOK": "Norwegian krone",
    "NPR": "Nepalese rupee",
    "NZD": "New Zealand dollar",
    "OMR": "Omani rial",
    "PAB": "Panamanian balboa",
    "PEN": "Peruvian sol",
    "PGK": "Papua New Guinean kina",
    "PHP": "Philippine peso",
    "PKR": "Pakistani rupee",
    "PLN": "Polish złoty",
    "PYG": "Paraguayan guarani",
    "QAR": "Qatari riyal",
    "RON": "Romanian leu",
    "RSD": "Serbian dinar",
    "RUB": "Russian ruble",
    "RWF": "Rwandan franc",
    "SAR": "Saudi riyal",
    "SBD": "Solomon Islands dollar",
    "SCR": "Seychellois rupee",
    "SDG": "Sudanese pound",
    "SEK": "Swedish krona",
    "SGD": "Singapore dollar",
    "SHP": "Saint Helena pound",
    "SLL": "Sierra Leonean leone",
    "SOS": "Somali shilling",
    "SRD": "Surinamese dollar",
    "SSP": "South Sudanese pound",
    "STN": "Dobra",
    "SYP": "Syrian pound",
    "SZL": "Lilangeni",
    "THB": "Thai baht",
    "TJS": "Tajikistani somoni",
    "TMT": "Turkmenistan manat",
    "TND": "Tunisian dinar",
    "TOP": "Tongan paʻanga",
    "TRY": "Turkish lira",
    "TTD": "Trinidad and Tobago dollar",
    "TWD": "New Taiwan dollar",
    "TZS": "Tanzanian shilling",
    "UAH": "Ukrainian hryvnia",
    "UGX": "Ugandan shilling",
    "USD": "United States dollar",
    "UYU": "Uruguayan peso",
    "UZS": "Uzbekistani soʻm",
    "VES": "Bolívar",
    "VND": "Vietnamese đồng",
    "VUV": "Vanuatu vatu",
    "WST": "Samoan tālā",
    "XAF": "Central African CFA franc",
    "XCD": "Eastern Caribbean dollar",
    "XOF": "West African CFA franc",
    "XPF": "CFP franc",
    "YER": "Yemeni rial",
    "ZAR": "South African rand",
    "ZMW": "Zambian kwacha",
    "ZWL": "Zimbabwe Dollar",
}

# Corrections to the places data. Each is a fact about ISO 4217, not a preference:
#  - AAD is listed for Antarctica but is not an ISO currency (nothing there is paid in it);
#  - Sierra Leone replaced the leone SLL with SLE in 2022 and Zimbabwe replaced ZWL with ZWG in 2024. The retired codes stay
#    valid (a salary recorded years ago may be in them), and the new ones, which the data predates, are added.
REMOVED = {"AAD"}
ADDED = {"SLE": "Sierra Leonean leone", "ZWG": "Zimbabwe Gold"}

CURRENCIES: dict[str, str] = {**{c: n for c, n in _FROM_PLACES_DATA.items() if c not in REMOVED}, **ADDED}

# Shown first in the picker: the ones most salaries are in. (Everything else follows, alphabetically by code.)
COMMON = ("USD", "EUR", "GBP", "CAD", "AUD", "CHF", "JPY", "INR", "CNY", "SGD", "NZD", "SEK", "NOK", "DKK", "BRL", "MXN", "ZAR")


def normalize_currency(raw: str) -> str:
    """"usd ", "Usd" and "USD" are all USD."""
    return raw.strip().upper()
